### PR TITLE
Revamped navigator tree select

### LINKED ISSUE #5888: Navigator shift-click to multiselect is broken if condensed rows are involved
**Problem**
In the sample project, we wanted to wrap two siblings into a column. This worked by CMD clicking, but Shift-Clicking (the default behaviour I'd argue, even if the result is the same) did not work!

**Solution**
Fix it!

### PR DESCRIPTION
**Pull request by ruggi**
**Problem:**

The navigator with the new tree generation used to support condensed rows does not support correctly the whole set of selection operations all navigator entries should support (cmd+click, shift+click).

**Fix:**

Add a common wrapper (`NavigatorRowClickableWrapper`) and hook (`useGetNavigatorClickActions`) that unify the behavior so it's possible to do additive selection and range selections on navigator entries, regardless of their structure.

**Manual Tests:**
I hereby swear that:

- [x] I opened a hydrogen project and it loaded
- [x] I could navigate to various routes in Preview mode

Fixes #5888

### CODE REVIEW

File: editor/src/components/navigator/navigator-item/map-counter.tsx [hunk 1]
```diff
@@ -83,15 +83,19 @@ export const MapCounter = React.memo((props: MapCounterProps) => {
...
-      return
-    }
-    const nextValue = getNextOverrideValue(overrideStatus, countOverride, nrChildren)
-    if (nextValue !== countOverride) {
-      dispatch([setMapCountOverride(props.elementPath, nextValue)])
-    }
-  }, [props.elementPath, dispatch, overrideStatus, countOverride, nrChildren])
+  const onClick = React.useCallback(
+    (e: React.MouseEvent) => {
+      e.stopPropagation()
```
Comment (ruggi) [inline editor/src/components/navigator/navigator-item/map-counter.tsx:88]: the only thing that changed here

File: editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx [hunk 2]
```diff
@@ -104,24 +107,26 @@ export const CondensedEntryItemWrapper = React.memo(
...
-              key={EP.toString(entry.elementPath)}
-              entry={entry}
-              showSeparator={showSeparator}
-              wholeRowInsideSelection={wholeRowInsideSelection}
-              rowContainsSelection={rowContainsSelection}
-              rowRootSelected={rowRootSelected}
-            />
-          )
-        })}
+        <NavigatorRowClickableWrapper row={props.navigatorRow}>
```
Comment (ruggi) [inline editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx:110]: nothing has changed here, only the wrapper component is added

File: editor/src/components/navigator/navigator-item/navigator-item-clickable-wrapper.tsx [hunk 3]
```diff
@@ -0,0 +1,328 @@
...
+        )
+      } else {
+        // when we click on an already selected item we should force vscode to navigate there
+        if (selected && highlightBounds != null) {
+          sendMessage(
+            toVSCodeExtensionMessage(
+              selectedElementChangedMessageFromHighlightBounds(highlightBounds, 'force-navigation'),
+            ),
+          )
+        }
```
Comment (ruggi) [inline editor/src/components/navigator/navigator-item/navigator-item-clickable-wrapper.tsx:106]: ported verbatim from the legacy select implementation

File: editor/src/components/navigator/navigator-item/navigator-item-clickable-wrapper.tsx [hunk 4]
```diff
@@ -0,0 +1,328 @@
...
+      )
+      if (isConditionalClauseNavigatorEntry(navigatorEntry)) {
+        return conditionalOverrideUpdateForClause(navigatorEntry.clause, elementMetadata)
+      } else {
+        return conditionalOverrideUpdateForPath(path, metadata)
+      }
+    },
+    'useConditionalOverrideUpdate conditionalOverrideUpdate',
+  )
+}
```
Comment (ruggi) [inline editor/src/components/navigator/navigator-item/navigator-item-clickable-wrapper.tsx:274]: ported verbatim from the legacy select implementation (but made into a hook)

File: editor/src/components/navigator/navigator-item/navigator-item-clickable-wrapper.tsx [hunk 5]
```diff
@@ -0,0 +1,328 @@
...
+      return 'no-update'
+    } else if (isDefaultBranchOfConditional(conditionalCase, parentMetadata)) {
+      return 'clear-override'
+    } else {
+      return conditionalCase
+    }
+  }
+
+  return 'no-update'
+}
```
Comment (ruggi) [inline editor/src/components/navigator/navigator-item/navigator-item-clickable-wrapper.tsx:309]: ported verbatim from the legacy select implementation

File: editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx [hunk 6]
```diff
@@ -288,6 +284,20 @@ const CondensedEntryItemContent = React.memo(
       ])
     }, [props.entry, dispatch, highlightedViews])
 
+    const getClickActions = useGetNavigatorClickActions(
```
Comment (balazsbajorics) [inline editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx:287]: shouldn't this be using the clickable wrapper too?

**Review by balazsbajorics — APPROVED** [review]

**Review by bkrmendy — APPROVED** [review]

File: editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx (hunk 6 above)
Comment (ruggi) [reply editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx:287]: that's a negatory, because they would kick each other

Comment (ruggi) [reply editor/src/components/navigator/navigator-item/navigator-condensed-entry.tsx:287]: suboptimal, but if you look at the git history that's why I factored out the actions functions _and_ renamed the wrapper to `Navigator__Row__ClickableWrapper`

File: editor/src/components/navigator/navigator-item/navigator-item.tsx [hunk 7]
```diff
@@ -215,8 +116,8 @@ const collapseItem = (
   elementPath: ElementPath,
   e: React.MouseEvent<HTMLDivElement>,
 ) => {
-  dispatch([EditorActions.toggleCollapse(elementPath)], 'leftpane')
   e.stopPropagation()
+  dispatch([EditorActions.toggleCollapse(elementPath)], 'leftpane')
```
Comment (seanparsons) [inline editor/src/components/navigator/navigator-item/navigator-item.tsx:120]: Huh? What did this fix?

**Review by seanparsons — APPROVED** [review]

File: editor/src/components/navigator/navigator-item/navigator-item.tsx (hunk 7 above)
Comment (ruggi) [reply editor/src/components/navigator/navigator-item/navigator-item.tsx:120]: oh – nothing really, my OCD while cruising through all the handlers desperately wanted to have that `e.stopPropagation()` at the beginning of the funciton like all others, since there should be no reason for it to follow the dispatch

Comment (balazsbajorics) [reply editor/src/components/navigator/navigator-item/navigator-item.tsx:120]: oh I thought there's one more browser API gotcha I need to keep in mind
