### PR TITLE
Navigator html + head fixes

### LINKED ISSUE #5291: Tweak `html` and `head` element handling in Navigator
- The `html` row in the navigator should by default be non-selectable (using the lock icon), so `body` becomes the ‘outermost div’ you can select
- The `head` element should not expand its children by default

### PR DESCRIPTION
**Pull request by ruggi**
**Problem:**

The `html` entry of the navigator should be auto-locked, and the `head` entry should be collapsed by default.

**Fix:**

- Disable the select callback for the `html` entry
- Add the `html` entry check in `updateSimpleLocks`

**Manual Tests:**
I hereby swear that:

- [x] I opened a hydrogen project and it loaded
- [x] I could navigate to various routes in Preview mode

Fixes #5291

### CODE REVIEW

File: editor/src/components/navigator/navigator.tsx [hunk 1]
```diff
@@ -323,3 +328,53 @@ export const NavigatorComponent = React.memo(() => {
...
+
+  React.useEffect(() => {
+    const newCollapsedViews = Object.keys(elementNamesByElementPath).filter((path) => {
+      return (
+        // the collapsed views don't already contain the element
+        !collapsedPaths.has(path) &&
+        // the collapsed view wasn't already collapsed before
+        previouslyCollapsed[path] == null &&
+        // the element is a `head`
+        elementNamesByElementPath[path] === 'head'
```
Comment (liady) [inline editor/src/components/navigator/navigator.tsx:367]: won't that result only in the "head" path (i.e an array with max length of 1)?

Comment (ruggi) [reply editor/src/components/navigator/navigator.tsx:367]: If you mean it will only contain the `<head>` path of `<head><foo /><bar /></head>` (and not `foo` and `bar`), yes but that's desired.
Or am I misunderstanding and you mean something else?

File: editor/src/components/editor/use-default-collapsed-views.tsx [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import { isJSXElement } from '../../core/shared/element-template'
+import * as EP from '../../core/shared/element-path'
+import { addCollapsedViews } from './actions/action-creators'
+
+export function useDefaultCollapsedViews() {
+  const dispatch = useDispatch()
+
+  // keep track of the previously collapsed element paths, or they will be re-collapsed
+  type PreviouslyCollapsed = { [path: string]: boolean }
+  const [previouslyCollapsed, setPreviouslyCollapsed] = React.useState<PreviouslyCollapsed>({})
```
Comment (balazsbajorics) [inline editor/src/components/editor/use-default-collapsed-views.tsx:14]: could this be a React.useRef? with the current value updated in the useEffect

Comment (ruggi) [reply editor/src/components/editor/use-default-collapsed-views.tsx:14]: I guess it can! sec

**Review by balazsbajorics — APPROVED** [review]

**Review by liady — APPROVED** [review]

File: editor/src/components/navigator/navigator-item/navigator-item.tsx [hunk 3]
```diff
@@ -739,18 +740,40 @@ export const NavigatorItem: React.FunctionComponent<
...
+      const isHTMLTagElement =
+        element != null &&
+        isRight(element.element) &&
+        isJSXElement(element.element.value) &&
+        element.element.value.name.baseVariable === 'html'
+
+      return !isHTMLTagElement
+    },
+    'NavigatorItem canBeSelected',
+  )
```
Comment (Rheeseyb) [inline editor/src/components/navigator/navigator-item/navigator-item.tsx:760]: Since we already have the functionality, we should be using the locking mechanism for this. You can add a check into `updateSimpleLocks` <https://github.com/concrete-utopia/utopia/blob/master/editor/src/core/shared/element-locking.ts#L8-L33>

**Review by Rheeseyb — APPROVED** [review]
