### PR TITLE
fix(fileitem.tsx) Handle file names with trailing slashes

### LINKED ISSUE #602: Regression: Importing a Github project now clears folder names

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #602 

**Problem:**
Folder names with a trailing slash were being rendered as empty strings

**Fix:**
Filter empty values from the result of the string split we were using. I've also removed a comment questioning the allowance of folders with a dot in their names since folders prefixed with a dot are definitely allowed.

### CODE REVIEW

File: editor/src/components/filebrowser/fileitem.tsx [hunk 1]
```diff
@@ -231,8 +230,7 @@ class FileBrowserItemInner extends React.PureComponent<
         isRenaming: props.renamingTarget === props.path,
       }
     }
-    // todo this is not very safe. should it be not allowed to use . in folder names?
-    const pathParts = dropLeadingSlash(props.path).split('/')
+    const pathParts = props.path.split('/').filter((s) => s !== '')
```
Comment (balazsbajorics) [inline editor/src/components/filebrowser/fileitem.tsx:233]: hmm this is interesting. so if I name a folder `something/like/this` it becomes three nested folders?

Comment (balazsbajorics) [reply editor/src/components/filebrowser/fileitem.tsx:233]: is that in line with how folders work on "unix" ?

Comment (seanparsons) [reply editor/src/components/filebrowser/fileitem.tsx:233]: I think you can escape them with a backslash...

**Review by balazsbajorics — APPROVED** [review]

**Review by enidemi — APPROVED** [review]

File: editor/src/components/filebrowser/fileitem.tsx (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/components/filebrowser/fileitem.tsx:233]: Homer Disappearing

Comment (Rheeseyb) [reply editor/src/components/filebrowser/fileitem.tsx:233]: I've just tested with `mkdir` and inside my file browser (Dolphin) and it doesn't seem to be possible to make non-nested directories with forward slashes (even when escaped)

Comment (Rheeseyb) [reply editor/src/components/filebrowser/fileitem.tsx:233]: https://stackoverflow.com/a/9847573

**Review by seanparsons — APPROVED** [review]
