### PR TITLE
Github Project Import

### LINKED ISSUE #494: Basic client side github project to utopia project conversion
Follow on from #493

After downloading a github repo, the client should extract the archive, then iterate through it to create a utopia project (uploading assets as it goes). Failing to upload an asset should not cause the process to fail (for this pass we should just log an error to the console).

Upon completion, the new project files should replace the currently open project in the editor (for this pass only, so that we can see that it has worked)

### LINKED ISSUE #495: Show some form of loading message during github project conversion, and prevent any form of editor interaction until the conversion has finished
Follow on from #494

When performing a github project import, the editor should block interaction and show some form of loading message / screen. Once the project import has completed, the editor should then load that newly created project, and trigger a save to the server.

MN addition: loading screen. (Also covered by #509 )

image

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #494 
Fixes #495 

**Problem:**
We want to import and load a github project.

**Fix:**
Trigger a repo download when hitting the url `/p?github_owner=<owner>&github_repo=<repo>` as part of the editor start up. After downloading the repo, we iterate through the contents to generate a `ProjectContents` object, along with an array of assets to upload to the server. To handle the next stage, a `createNewProjectFromImportedProject` flow was added, which generates a `PersistentModel`, a project ID, and then uploads everything to the server.

A lot of this flow was forced by the fact local projects don't support arbitrary assets, meaning that to import a github project we require the user to be signed in so that the assets can be immediately uploaded.

**Commit Details:**
- Extracted some of the image and asset extraction logic to a new file `core/shared/file-utils.ts`, including the stripping of the mime type from the start of assets' base64 (we were already doing this everywhere)
- `downloadGithubRepo` in `server.ts` now returns a `Either` of the zipped response or an error message (rather than trying to do some project conversion)
- Added `project-import.ts` for iterating through a zipped git repo and creating the `ProjectContents` object, along with an array of assets to upload
- Added a helper function for creating `PersistentModel`s from a `ProjectContents`
- Made a very bad assumption that `fileTypeFromFileName` should return `'CODE_FILE'` for files with no extension, with a `FIXME` in place because that definitely needs changing
- Added `createNewProjectFromImportedProject` to `persistence.ts`, which forces a server save of the assets and project as part of the load
- Trigger the whole flow in `editor.tsx` when determining whether to create or load a project
- Restrict github project download on the server side to logged in users only to somewhat mitigate abuse

**Note** that this doesn't handle error cases very well at all, but that is due to be tackled in #509. ~This also just shows the regular loading animation until it is completed, which is due to be fixed in #495~ This now replaces the message in the loading screen to indicate what is happening.

### CODE REVIEW

**Comment by Rheeseyb** [comment]
Ok I've made a change to quickly support displaying a loading message. Basically I added an `id` to the 'Utopia' text element in the loading screen, and then a function for replacing the text there, so that during loading the text is updated as follows:
At the start:
Screenshot_20200911_174946

When triggering the download:
Screenshot_20200911_175405

When converting to a Utopia project:
Screenshot_20200911_175336

File: editor/src/core/model/project-import.ts [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+        }
+        case 'UI_JS_FILE':
+        case 'CODE_FILE':
+          const loadedFile = await attemptedTextFileLoad(shiftedFileName, file)
+          if (loadedFile == null) {
+            // FIXME Client should show an error if loading a text file fails
+            console.error(`Failed to parse file ${shiftedFileName} as a text file`)
+          } else {
+            if (expectedFileType === 'UI_JS_FILE') {
+              // TODO We really need a way to represent unparsed files, or a way to separate the parsed file from the contents
```
Comment (seanparsons) [inline editor/src/core/model/project-import.ts:103]: Subsequent work or a nice to have?

**Review by seanparsons — APPROVED** [review]

File: editor/src/core/model/project-import.ts (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/core/model/project-import.ts:103]: Hmmm somewhere in between. Not having that makes the code quite clunky in a number of places.
