### PR TITLE
Fix/canvas shortcut copy elements

### LINKED ISSUE #1189: Cut (of "cut and paste") is no longer working
STR
- Insert View
- Right-click on it
- Cut

Observed: parent element gets selected (correct), but cut element persists

Expected: it, well, cuts.

### PR DESCRIPTION
**Pull request by enidemi**
Fixes #1189

**Problem:**
Cut/copy/paste doesn't work on non-storyboard elements. The element copied to the clipboard is a `null`.

**Fix:**
Updating `createClipboardDataFromSelectionNewWorld` to handle different files.

**Commit Details:**
- using `normalisePathToUnderlyingTarget` to find the filepath for templatepath
- added a test

### CODE REVIEW

File: editor/src/utils/clipboard.ts [hunk 1]
```diff
@@ -150,28 +160,39 @@ export function createDirectInsertImageActions(
...
   }
-  const parseSuccess = openUIJSFile.fileContents.parsed
   const filteredSelectedViews = editor.selectedViews.filter((view) => {
     return R.none((otherView) => EP.isDescendantOf(view, otherView), editor.selectedViews)
   })
-  const utopiaComponents = getUtopiaJSXComponentsFromSuccess(parseSuccess)
-  const jsxElements = filteredSelectedViews.map((view) => {
-    return findElementAtPath(view, utopiaComponents)
-  })
+  const jsxElements = stripNulls(
```
Comment (seanparsons) [inline editor/src/utils/clipboard.ts:175]: Can use `mapDropNulls` for this.

**Review by seanparsons — APPROVED** [review]

**Review by balazsbajorics — APPROVED** [review]

File: editor/src/utils/clipboard.ts [hunk 2]
```diff
@@ -150,28 +160,39 @@ export function createDirectInsertImageActions(
 
 export function createClipboardDataFromSelectionNewWorld(
```
Comment (Rheeseyb) [inline editor/src/utils/clipboard.ts:161]: Might as well rename this to remove the `NewWorld` whilst you're here (assuming the old world version no longer exists)

**Review by Rheeseyb — APPROVED** [review]

File: editor/src/utils/clipboard.ts (hunk 2 above)
Comment (enidemi) [reply editor/src/utils/clipboard.ts]: fixed
