### PR TITLE
Fix/duplicate errors

### LINKED ISSUE #882: Duplicating an element with children fails
STR: Duplicate a view with children

Project: https://utopia.pizza/p/fd406324-dawn-snout/

```
webpack://utopia/./src/core/shared/element-template.tsx?:558 Uncaught TypeError: Cannot read property 'type' of undefined
    at Object.isJSXElement (webpack://utopia/./src/core/shared/element-template.tsx?:558)
    at eval (webpack://utopia/./src/core/model/element-metadata-utils.ts?:983)
    at Array.map (<anonymous>)
    at duplicateElementMetadata (webpack://utopia/./src/core/model/element-metadata-utils.ts?:975)
    at eval (webpack://utopia/./src/core/model/element-metadata-utils.ts?:987)
    at Array.map (<anonymous>)
    at duplicateElementMetadata (webpack://utopia/./src/core/model/element-metadata-utils.ts?:975)
    at Object.duplicateElementMetadataAtPath (webpack://utopia/./src/core/model/element-metadata-utils.ts?:1017)
    at eval (webpack://utopia/./src/components/canvas/canvas-utils.ts?:1491)
    at Object.foldParsedTextFile (webpack://utopia/./src/core/shared/project-file-types.ts?:161)
```

### LINKED ISSUE #884: Duplicating an element with children fails (II)
Same as before, but with a different error message this time:

3webpack://utopia/./src/core/model/element-template-utils.ts?:21 Uncaught (in promise) Error: Found duplicate UID: '054'. Suspicious action(s): PASTE_JSX_ELEMENTS
    at extractUid (webpack://utopia/./src/core/model/element-template-utils.ts?:21)
    at Object.fastForEach (utils.ts:18)
    at extractUid (webpack://utopia/./src/core/model/element-template-utils.ts?:15)
    at Object.fastForEach (utils.ts:18)
    at extractUid (webpack://utopia/./src/core/model/element-template-utils.ts?:15)
    at Object.fastForEach (utils.ts:18)
    at extractUid (webpack://utopia/./src/core/model/element-template-utils.ts?:15)
    at Object.fastForEach (utils.ts:18)
    at extractUid (webpack://utopia/./src/core/model/element-template-utils.ts?:15)
    at eval (webpack://utopia/./src/core/model/element-template-utils.ts?:34)

### PR DESCRIPTION
**Pull request by enidemi**
Fixes #882 
Fixes #884 

**Problem:**
Duplicating an element while dragging was throwing error for creating duplicated UIDs with element children. 
Duplicating using the shortcut was throwing errors for not finding child elements for metadata duplication.

I made 2 PRs because these bugs are related.

**Fix:**
Drag duplication didn't replace the descendant UIDs on the jsx elements, that's why it was throwing error. Duplicating with a shortcut already creates new UIDs for every descendant.
After the JSX element insertion the metadata is modified for later frame update purposes. After my fix to the drag duplication with `guaranteeUniqueUids` I had the error about metadata duplication. It was completely wrong, because it tried to replace only the element path, but all descendants have completely different path with new uids. Since the duplicated children metadata is not used later, I just removed it.

**Commit Details:**
- fix in canvas-utils to avoid duplicated uids for children and descendants
- removing the children metadata from duplication
- test for canvas-action `createDragState` to see if the duplication action is successfully updating the editor state

### CODE REVIEW

File: editor/src/core/model/element-metadata-utils.ts [hunk 1]
```diff
@@ -1310,7 +1295,7 @@ export const MetadataUtils = {
         ...element,
         templatePath: newTemplatePath,
         element: newElementInner,
-        children: duplicatedChildren,
+        children: [], // all descendants have new UID-s
```
Comment (balazsbajorics) [inline editor/src/core/model/element-metadata-utils.ts:1298]: does this break anything on the UI? afaik we create this mock metadata so that things like the navigator can already render the new elements even before the dom report / spy report arrives one frame later.

Comment (enidemi) [reply editor/src/core/model/element-metadata-utils.ts:1298]: I think the metadata is used to have the updateFrames run correctly in the next step. 
The navigator is hard to decide because when elements change in general it's not so smooth.

**Review by balazsbajorics — APPROVED** [review]

**Review by Rheeseyb — APPROVED** [review]

**Review by seanparsons — APPROVED** [review]
