### PR TITLE
Re-export support.

### LINKED ISSUE #1737: Parser is broken for `export const thing = 'hello'`
If a file contains `export const thing = 'hello'`, that should show up in the parsed file's `exportDetails`, but doesn't, meaning it cannot be imported by another file running in the canvas

### PR DESCRIPTION
**Pull request by seanparsons**
Fixes #1737

**Problem:**
Currently Utopia does not recognise or support module re-exports at all.

**Fix:**
This change reworks the entire set of export types so as to get a more granular and accurate representation of the various cases, as well as adding extra cases for re-exports which didn't particularly mesh well with the original types. One possible future for these new types is that they could be handled similarly to arbitrary blocks, being executed and then having their results accumulated at the end. As it's possible that the current handling does not handle particularly esoteric cases like a chain of destructured exports.

Re-exports in the canvas just defer onwards to the module that is being re-exported and then includes the values into the current scope.

**Limitations:**
Currently the `EXPORT_DESTRUCTURED_ASSIGNMENT` case will cause the functionality to degrade slightly in using the fallback require on the canvas. Handling those more correctly in the way exports have been handled so far would be difficult because of the dependency on an expression on the right hand side of the export statement.

**Commit Details:**
- Completes the fix for #1737.
- Adds `@babel/plugin-proposal-export-namespace-from` to support
  the ECMAScript 2021 re-export into a namespace.
- Changed `resolveTextFiles` to make it more closely approximate
  what real world projects would do and look like, along with
  fixing some of the test data that was affected by this change.
- Completely rewrote the various types that represent exports to be
  more specific to the various cases that arise, along with adding
  types for re-exports.
- Canvas export handling updated for new types.
- `getExportedComponentImports` fixed to handle new export types.
- `transformToCommonJS` utilises the above mentioned Babel plugin
  for namespaced imports.
- `addStoryboardFileToProject` updated for new export types.
- Fixed some of the `Arbitrary` instances to generate the updated types.
- Updated `getModifiersForComponent`, `detailsFromExportAssignment`,
  `detailsFromExportDeclaration` and `parseCode` to handle the new
  export types.

### CODE REVIEW

File: editor/src/components/canvas/ui-jsx-canvas.tsx [hunk 1]
```diff
@@ -361,29 +370,123 @@ export const UiJsxCanvas = betterReactMemo(
...
+                  filteredScopeKey: string,
+                  scopeKey: string,
+                  scopeToWorkWith: MapLike<any>,
+                ): void {
+                  if (scopeKey in scopeToWorkWith) {
+                    filteredScope[filteredScopeKey] = scopeToWorkWith[scopeKey]
                   }
                 }
+
+                function addToFilteredScope(filteredScopeKey: string, scopeKey: string): void {
```
Comment (balazsbajorics) [inline editor/src/components/canvas/ui-jsx-canvas.tsx:388]: can this be moved to be a top level function?

**Review by balazsbajorics — APPROVED** [review]

File: editor/src/components/canvas/ui-jsx-canvas.tsx (hunk 1 above)
Comment (seanparsons) [reply editor/src/components/canvas/ui-jsx-canvas.tsx:388]: It could but the two scopes would have to be pulled up into parameters.

Comment (balazsbajorics) [reply editor/src/components/canvas/ui-jsx-canvas.tsx:388]: I'm just a bit sad that the ui-jsx-canvas render function is becoming this unholy amalgam of module resolution + entry point for the canvas rendering

Comment (seanparsons) [reply editor/src/components/canvas/ui-jsx-canvas.tsx:388]: A better solution would be pull the whole block of export handling into a top level function, I _think_ that would work.

File: editor/src/components/canvas/ui-jsx-canvas-bugs.spec.tsx [hunk 2]
```diff
@@ -378,7 +378,7 @@ export default function () {
         <div
           id=\\"canvas-container\\"
           style=\\"position: absolute;\\"
-          data-utopia-valid-paths=\\"storyboard-entity storyboard-entity/scene-1-entity storyboard-entity/scene-1-entity/app-entity\\"
+          data-utopia-valid-paths=\\"storyboard-entity storyboard-entity/scene-1-entity storyboard-entity/scene-1-entity/app-entity storyboard-entity/scene-1-entity/app-entity:app-outer-div storyboard-entity/scene-1-entity/app-entity:app-outer-div/card-instance storyboard-entity/scene-1-entity/app-entity:app-outer-div/d7f\\"
```
Comment (Rheeseyb) [inline editor/src/components/canvas/ui-jsx-canvas-bugs.spec.tsx:381]: Nice!

**Review by Rheeseyb — APPROVED** [review]

File: editor/src/components/canvas/ui-jsx-canvas.tsx (hunk 1 above)
Comment (seanparsons) [reply editor/src/components/canvas/ui-jsx-canvas.tsx]: Fixed in 5591ee12.
