### PR TITLE
Corrected the observed value being used when resizing

### LINKED ISSUE #1679: Dragging to resize absolute elements is incorrectly updating width and height

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #1679 

**Problem:**
When resizing the height via the new canvas menu controls, we were incorrectly using the wrong observed value

**Fix:**
`width` -> `height`

### CODE REVIEW

**Review by balazsbajorics — APPROVED** [review]

File: editor/src/components/canvas/canvas-utils.ts [hunk 1]
```diff
@@ -3020,7 +3020,7 @@ export function getObservableValueForLayoutProp(
       case 'Height':
       case 'minHeight':
       case 'maxHeight':
-        return elementMetadata.localFrame?.width
+        return elementMetadata.localFrame?.height
```
Comment (maltenuhn) [inline editor/src/components/canvas/canvas-utils.ts:3023]: 🤦
