### PR TITLE
Fix Code Editor Saving

### LINKED ISSUE #534: cmd+s doesn't seem to reliably save the project
From Slack:

> I press cmd + s
> then I wait a bit
> then I press reload
> warning dialog comes up
> I press reload anyway
> data is lost
> what I usually do is I copy my app ui js contents
> and keep pressing cmd + s + reload until the dialog does not come up

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #534 

**Problem:**
Saving when the code editor was focused wasn't actually including the updated model in the save. As well as this, we were seemingly always telling the user that their project had unsaved changed.

**Fix:**
The code editor `cmd`+`s` flow was using a poorly named function that went outside of the correct saving flow. This function is actually for forcing through the currently queued save, which would have been queued up before the model had been updated. To fix this part of the issue we just dispatch the correct action instead of trying to circumvent the correct flow.
Also, for some reason changing the cursor position was treated as a non-transient action, meaning that in itself was constantly queuing up saves to the server, so that's no longer the case.

**Commit Details:**
- Dispatch a `SAVE_CURRENT_FILE` action from `script-editor.tsx` when forcibly saving, which triggers the "force save" process when that set of actions are handled
- Rename (and no longer export) the poorly named `forceServerSave` to `forceQueuedSave`, since that is an internal only function for forcing through the last queued save
- Made `SAVE_CURSOR_POSITION` a transient action

### CODE REVIEW

**Review by enidemi — APPROVED** [review]

File: editor/src/components/editor/actions/action-utils.ts [hunk 1]
```diff
@@ -131,7 +132,6 @@ export function isTransientAction(action: EditorAction): boolean {
     case 'UNWRAP_LAYOUTABLE':
     case 'UPDATE_JSX_ELEMENT_NAME':
     case 'SET_ASPECT_RATIO_LOCK':
-    case 'SAVE_CURSOR_POSITION':
```
Comment (balazsbajorics) [inline editor/src/components/editor/actions/action-utils.ts:134]: oops?

File: editor/src/components/editor/actions/action-utils.ts [hunk 2]
```diff
@@ -131,7 +132,6 @@ export function isTransientAction(action: EditorAction): boolean {
...
     case 'SET_CODE_EDITOR_THEME':
```
Comment (balazsbajorics) [inline editor/src/components/editor/actions/action-utils.ts:135]: while we are here... this also sounds like it shouldn't be in the undo flow? :)

**Review by balazsbajorics — APPROVED** [review]

File: editor/src/components/editor/actions/action-utils.ts (hunk 2 above)
Comment (Rheeseyb) [reply editor/src/components/editor/actions/action-utils.ts:135]: Yeah... this is part of project "Fix the damn undo flow". The problem is "Transient" functions are used to label things that we want to add to the undo stack and that we want to trigger a save, both of which should definitely be separate things. I'm going to say we leave this until we finally get a chance to tackle that as a whole.

File: editor/src/components/editor/actions/action-utils.ts (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/components/editor/actions/action-utils.ts:134]: I can see why we want to store the cursor position when saving, but having _every single_ cursor change trigger a save was nightmare fuel.
