### PR TITLE
Correctly handle wrapping the root element

### LINKED ISSUE #1638: Wrapping root element of a component doesn’t work
Selecting the root element of `App`, right clicking, selecting "Wrap in" followed by "div" will fail to wrap the selected element in a `div`, and will instead add a new `div` as a child of the `App` instance

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #1638 

**Problem:**
When attempting to use the "Wrap in" options from the floating menu whilst targeting the root element of a component, the result is a new element added as a child of an instance of the component.

**Fix:**
The problem here is that we are blindly using the parent parent, and not checking if that parent path is on the instance. I think we might have some other cases of this problem elsewhere in the code, but for now I've fixed the handling of that parent path here by explicitly checking if the target was the root element of the insertion parent, and if so we use `transformJSXComponentAtPath` to insert a new root element above that.

### CODE REVIEW

File: editor/src/components/editor/actions/actions.ts [hunk 1]
```diff
@@ -2143,7 +2156,9 @@ export const UPDATE_FNS = {
             editor.projectContents,
             editor.nodeModules.files,
             uiFileKey,
-            parentPath,
+            targetThatIsRootElementOfCommonParent != null
+              ? targetThatIsRootElementOfCommonParent
+              : parentPath,
```
Comment (balazsbajorics) [inline editor/src/components/editor/actions/actions.ts:2161]: why not 
```suggestion
            targetThatIsRootElementOfCommonParent ?? parentPath,
```

**Review by balazsbajorics — APPROVED** [review]

File: editor/src/components/editor/actions/actions.ts (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/components/editor/actions/actions.ts:2161]: Ha! No reason at all, good catch
