### PR TITLE
Fix misplaced conditionals in the navigator root

### LINKED ISSUE #3554: Fix misplaced conditionals in navigator root

### PR DESCRIPTION
**Pull request by ruggi**
Fixes #3554 

**Problem:**

Conditional elements at the root of the navigator would be displayed always at the top regardless of their position in the actual tree.

For example, this tree
```
div1
conditional
div2
```

would result in the navigator displaying
```
conditional
div1
div2
```

**Fix:**

Use the (ordered) project tree as a base when populating the navigator items.

### CODE REVIEW

**Review by bkrmendy — APPROVED** [review]

File: editor/src/components/editor/store/store-deep-equality-instances.ts [hunk 1]
```diff
@@ -1035,6 +1038,8 @@ export function JSXElementChildKeepDeepEquality(): KeepDeepEqualityCall<JSXEleme
       return JSXTextBlockKeepDeepEquality(oldElement, newElement)
     } else if (isJSXFragment(oldElement) && isJSXFragment(newElement)) {
       return JSXFragmentKeepDeepEquality(oldElement, newElement)
+    } else if (isJSXConditionalExpression(oldElement) && isJSXConditionalExpression(newElement)) {
```
Comment (seanparsons) [inline editor/src/components/editor/store/store-deep-equality-instances.ts:1041]: Oooh, that's upsetting. Not the fix, but that this issue was in there.

Comment (ruggi) [reply editor/src/components/editor/store/store-deep-equality-instances.ts:1041]: Yeah it's... puzzling, it'd be nice to have the compiler yell at us there

Comment (seanparsons) [reply editor/src/components/editor/store/store-deep-equality-instances.ts:1041]: We could change this to a switch/case statement, which would make this slightly better, just not as nice as we still have to check both types.

File: editor/src/components/navigator/navigator-utils.ts [hunk 2]
```diff
@@ -179,7 +179,20 @@ export function getNavigatorTargets(
     }
   }
 
-  const canvasRoots = MetadataUtils.getAllStoryboardChildrenPathsUnordered(metadata)
+  function getCanvasRoots(trees: ElementPathTree[]): ElementPath[] {
```
Comment (seanparsons) [inline editor/src/components/navigator/navigator-utils.ts:182]: I wonder if this code should become an implementation of `getAllStoryboardChildrenPathsOrdered`.

**Review by seanparsons — APPROVED** [review]
