### PR TITLE
Fix/inspector layout percents

### LINKED ISSUE #904: inspector: % values in layout controls should work

### PR DESCRIPTION
**Pull request by enidemi**
Fixes #904 

**Problem:**
Element styles with percent values are not editable in the inspector, `width: '100%'` is shown as unknown type in non-editable control.

**Fix:**
Update the `parseFramePin` to use `LengthPercent` parser.
Also switched other layout parsers, margin/padding/min-maxwidth/flexgrow to their correct type based on the mdn docs.

**Commit Details:**
- update parser in css-utils
- fixed the new tests

### CODE REVIEW

File: editor/src/components/inspector/common/css-utils.ts [hunk 1]
```diff
@@ -4113,27 +4113,27 @@ const cssParsers: CSSParsers = {
...
-  flexShrink: parseCSSLength,
+  minWidth: parseCSSLengthPercent,
+  maxWidth: parseCSSLengthPercent,
+  minHeight: parseCSSLengthPercent,
+  maxHeight: parseCSSLengthPercent,
+  marginTop: parseCSSLengthPercent,
+  marginRight: parseCSSLengthPercent,
+  marginBottom: parseCSSLengthPercent,
+  marginLeft: parseCSSLengthPercent,
+  flexGrow: parseCSSUnitless,
```
Comment (balazsbajorics) [inline editor/src/components/inspector/common/css-utils.ts:4135]: nice catch!

**Review by balazsbajorics — APPROVED** [review]
nice!
