### PR TITLE
Fix editor crash on code error

### LINKED ISSUE #541: Errors in the code editor crash the editor
e.g. starting to type `const` at the top level of the `app.js` file of a new project, the editor crashed with:

```
ReferenceError: c is not defined
    at eval (eval at exports.SafeFunctionCurriedErrorHandler (code-exec-utils.ts:NaN), <anonymous>:3:1)
```

This is easy to reproduce on Staging, but I can't reproduce it when running the editor locally.

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #541 

**Problem:**
Code errors are currently bringing down the editor. This was because of the way we were handling error reporting, combined with the way React deals with error bounds. Effectively we were repeatedly re-rendering code that would capture errors, then throw them at a later point in time so that our error bounds could then catch them. However, since moving the error bounds up a level we no longer needed this, but still needed to make sure we weren't excessively running the code that caused the errors.

**Fix:**
Removed all of the threading of `reportError` through `ui-jsx-canvas.tsx`, since we were calling that in the error bounds anyway, and updated the error bounds to stop re-rendering of the children unless the `topLevelElements` had changed.

**Commit Details:**
- Added `getDerivedStateFromError` to `CanvasErrorBoundary`, which we would use to prevent the `UiJsxCanvas` from being rendered repeatedly if there was an existing runtime error. Also added a `componentDidUpdate` to clear the state if the `topLevelElements` had changed (since in that case we _would_ want to try rendering the `UiJsxCanvas` again)
- Binned off all excessive (and incorrect) error reporting that we were threading through, since we can now just leave the executed user code to throw
- Fixed up some of the test utils around generating metadata, since that was silently failing and squashing errors before
- Fixed up some default test data that was incorrectly interpolating strings, resulting in `props.[object Object]` :facepalm: 
- Fixed `jsx-attributes.spec.ts`, which was incorrectly passing in the wrong props (another silent failure from us squashing errors)

### CODE REVIEW

File: editor/src/components/canvas/canvas-component-entry.tsx [hunk 1]
```diff
@@ -42,12 +42,12 @@ export const CanvasComponentEntry = betterReactMemo(
...
-        <CanvasErrorBoundary uiFilePath={canvasProps.uiFilePath} reportError={props.reportError}>
-          <UiJsxCanvas
-            {...canvasProps}
-            clearErrors={props.clearErrors}
-            reportError={props.reportError}
-          />
+        <CanvasErrorBoundary
+          uiFilePath={canvasProps.uiFilePath}
+          reportError={props.reportError}
+          topLevelElementsIncludingScenes={canvasProps.topLevelElementsIncludingScenes}
```
Comment (seanparsons) [inline editor/src/components/canvas/canvas-component-entry.tsx:48]: I wonder if anything else needs to go in there like `imports` and `jsxFactoryFunction`, might be worth picking through `UiJsxCanvasProps`.

File: editor/src/utils/test-utils.ts [hunk 2]
```diff
@@ -182,6 +183,13 @@ export function createFakeMetadataForParseSuccess(success: ParseSuccess): Array<
       elementMetadata = createFakeMetadataForJSXElement(
         component.rootElement,
         TP.scenePath([BakedInStoryboardUID, createSceneUidFromIndex(index)]),
+        {
+          props: {
+            style: props[PP.toString(PathForResizeContent)] ? props.style : undefined,
```
Comment (seanparsons) [inline editor/src/utils/test-utils.ts:188]: Truthiness alert.

**Review by seanparsons — APPROVED** [review]

File: editor/src/components/canvas/canvas-component-entry.tsx (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/components/canvas/canvas-component-entry.tsx:48]: I was thinking we'd be best off using the raw code from the file here tbh

File: editor/src/utils/test-utils.ts (hunk 2 above)
Comment (Rheeseyb) [reply editor/src/utils/test-utils.ts:188]: Hmmm yes, good point. Will pull this out and make it not truthy

File: editor/src/components/canvas/canvas-component-entry.tsx (hunk 1 above)
Comment (seanparsons) [reply editor/src/components/canvas/canvas-component-entry.tsx:48]: Or that.

Comment (balazsbajorics) [reply editor/src/components/canvas/canvas-component-entry.tsx:48]: +1 to raw code

File: editor/src/components/canvas/ui-jsx-canvas.tsx [hunk 3]
```diff
@@ -160,11 +160,15 @@ export interface CanvasReactReportErrorCallback {
   reportError: (editedFile: string, error: Error, errorInfo?: React.ErrorInfo) => void
```
Comment (balazsbajorics) [inline editor/src/components/canvas/ui-jsx-canvas.tsx:160]: shouldn't this be deleted then?

File: editor/src/components/canvas/ui-jsx-canvas.tsx [hunk 4]
```diff
@@ -160,11 +160,15 @@ export interface CanvasReactReportErrorCallback {
...
 }
 
-export interface CanvasReactErrorCallback extends CanvasReactReportErrorCallback {
+export interface CanvasReactClearErrorsCallback {
   clearErrors: () => void
 }
 
-export type UiJsxCanvasPropsWithErrorCallback = UiJsxCanvasProps & CanvasReactErrorCallback
+export interface CanvasReactErrorCallback
```
Comment (balazsbajorics) [inline editor/src/components/canvas/ui-jsx-canvas.tsx:167]: could you use the same type annotation with the `&` instead of this empty interface extending a list of interfaces?

File: editor/src/components/canvas/ui-jsx-canvas.tsx (hunk 3 above)
Comment (Rheeseyb) [reply editor/src/components/canvas/ui-jsx-canvas.tsx:160]: It's still used elsewhere (e.g. in the `CanvasErrorBoundary` itself)

File: editor/src/components/canvas/ui-jsx-canvas.tsx [hunk 5]
```diff
@@ -1500,12 +1436,44 @@ function asErrorObject(e: unknown): Error {
...
+      hasError: true,
+    }
+  }
+
+  componentDidUpdate(
+    prevProps: CanvasErrorBoundaryProps,
+    _prevState: CanvasErrorBoundaryState,
+  ): void {
+    if (prevProps.topLevelElementsIncludingScenes !== this.props.topLevelElementsIncludingScenes) {
+      // eslint-disable-next-line react/no-did-update-set-state
```
Comment (balazsbajorics) [inline editor/src/components/canvas/ui-jsx-canvas.tsx:1463]: now that componentDidUpdate is the safe recommended way of reacting to prop changes, does this eslint rule still help us? https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-update-set-state.md

File: editor/src/components/canvas/ui-jsx-canvas.tsx (hunk 4 above)
Comment (Rheeseyb) [reply editor/src/components/canvas/ui-jsx-canvas.tsx]: Done

File: editor/src/utils/test-utils.ts (hunk 2 above)
Comment (Rheeseyb) [reply editor/src/utils/test-utils.ts]: Done (though it's still truthy, but it's a bit cleaner now)

File: editor/src/components/canvas/canvas-component-entry.tsx (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/components/canvas/canvas-component-entry.tsx]: Done

File: editor/src/components/canvas/ui-jsx-canvas.tsx (hunk 5 above)
Comment (Rheeseyb) [reply editor/src/components/canvas/ui-jsx-canvas.tsx:1461]: It's still a useful rule to have because the recommendation is to _only_ set the state _immediately_, and it must be wrapped in a condition. Having the rule will at the very least flag that the code has the potential to cause serious issues.

**Review by balazsbajorics — APPROVED** [review]
