### PR TITLE
Safer focusing handling.

### LINKED ISSUE #1632: **Regression: Every element has become focusable via double-click**
We previously had logic that determined what components could be focused via double-click (on canvas, and via navigator). It seems that's no longer the case, and as a result even a div can be focused.

### PR DESCRIPTION
**Pull request by seanparsons**
Fixes #1632

**Problem:**
It's possible to focus elements that shouldn't be focusable.

**Fix:**
Prevent the navigator items from attempting to focus ineligible items but also make the focusing action defend against rogue invocations as a final insurance measure.

**Commit Details:**
- Fixes #1632.
- Make the `focusComponent` handler in `NavigatorItem` only attempt to
  focus a component that is focusable.
- Made the `SET_FOCUSED_ELEMENT` more defensive by having it check if
  an element is focusable.
- Flip an if condition in `normalisePathToUnderlyingTarget` to avoid
  a double negative.

### CODE REVIEW

File: editor/src/components/navigator/navigator-item/navigator-item.tsx [hunk 1]
```diff
@@ -314,8 +314,10 @@ export const NavigatorItem: React.FunctionComponent<NavigatorItemInnerProps> = b
       [dispatch, elementPath, selected, isHighlighted],
     )
     const focusComponent = React.useCallback(() => {
-      dispatch([EditorActions.setFocusedElement(elementPath)])
-    }, [dispatch, elementPath])
+      if (isFocusedComponent) {
```
Comment (Rheeseyb) [inline editor/src/components/navigator/navigator-item/navigator-item.tsx:317]: Shouldn't this be `if (isFocusableComponent) {`?

Comment (seanparsons) [reply editor/src/components/navigator/navigator-item/navigator-item.tsx]: Why yes, yes it should, fixed in 650a8f4e.

**Review by Rheeseyb — APPROVED** [review]

**Review by enidemi — APPROVED** [review]
