### PR TITLE
fix(editor): remove error messages when deleting a file

### LINKED ISSUE #6300: Deleting a file with a syntax error leaves the canvas permanently broken
We should clear errors and re-evaluate the project when a file is deleted

### PR DESCRIPTION
**Pull request by liady**
**Problem:**
We currently clear errors only when a descriptor file is deleted. This can cause syntax errors to remain even after the file that they're in was deleted.

**Fix:**
Clear errors on every file delete

**Manual Tests:**
I hereby swear that:

- [X] I opened a hydrogen project and it loaded
- [X] I could navigate to various routes in Preview mode

Fixes #6300

### CODE REVIEW

**Review by gbalint — APPROVED** [review]

**Review by seanparsons — APPROVED** [review]

File: editor/src/components/editor/actions/actions.tsx [hunk 1]
```diff
@@ -4222,21 +4222,21 @@ export const UPDATE_FNS = {
...
-          const withUpdatedPropertyControls = {
+          // update property controls
+          nextEditor = {
             ...nextEditor,
             propertyControlsInfo: updatePropertyControlsOnDescriptorFileDelete(
               editor.propertyControlsInfo,
               action.filename,
             ),
           }
-          return removeErrorMessagesForFile(withUpdatedPropertyControls, action.filename)
```
Comment (Rheeseyb) [inline editor/src/components/editor/actions/actions.tsx:4237]: We must have been assuming that any other change would trigger a canvas render

**Review by Rheeseyb — APPROVED** [review]
