### PR TITLE
navigator fixes: full scroll, component icon only on hover

### LINKED ISSUE #5329: the navigator scroll is broken and hides the last element

### PR DESCRIPTION
**Pull request by maltenuhn**
**Problem:**
- Navigator didn't fully scroll
- Navigator clutter: component postfix icons were always visible
- missing componentInstance icon

**Fix:**
- Remove unnecessary `height: 100%` (we already had `flexGrow: 1`)
- show component postfix icons only on navigator hover
- add missing componentInstance icon (not yet used)

Fixes #5329

### CODE REVIEW

File: editor/src/uuiui/icons.tsx [hunk 1]
```diff
@@ -307,6 +307,12 @@ export const Icons = {
     width: 18,
     height: 18,
   }),
+  ComponentInstance: makeIcon({
+    category: 'element',
+    type: 'componentinstance',
+    width: 18,
+    height: 18,
+  }),
```
Comment (Rheeseyb) [inline editor/src/uuiui/icons.tsx:315]: Looks like this was committed accidentally

Comment (maltenuhn) [reply editor/src/uuiui/icons.tsx:315]: oh yeah, wanted to pull that to another branch but it's just an asset. Will update the PR

**Review by balazsbajorics — APPROVED** [review]
