### PR TITLE
Separate requested and resolved dependencies.

### LINKED ISSUE #535: Projects using `latest` in a package dependency end up failing in a jsdelivr call.
In this project there's a dependency on `@geist-ui/react`, which has a version of `latest`:
https://github.com/geist-org/react-getting-started/blob/master/package.json

In testing the Github import, it was observed that the editor makes a request to this URL:
`https://data.jsdelivr.com/v1/package/npm/@geist-ui/react@latest/flat`
Which fails with an error indicating that jsdelivr can only handle specific versions.

In conversation with Balazs he mentioned that this may be related to our support for a version of `*`, which if it is handled in the editor may provide a route to implementing a fix.

### PR DESCRIPTION
**Pull request by seanparsons**
Fixes #535

**Problem:**
Internally the editor treats dependencies without distinguishing between requested dependencies which may include bounds or keywords, but some aspects like the property controls can only handle resolved version numbers.

**Fix:**
Removed the old type for representing a dependency and replaced it with two representing the two cases and used those as appropriate.

**Commit Details:**
- Fixes #535.
- Get rid of the `NpmDependency` type and replace it with
  `RequestedNpmDependency` and `ResolvedNpmDependency` as appropriate.
  Which is to say the former is used "earlier" in the flow and represents
  a dependency taken directly from the user's `package.json` file.
  The latter is often then derived from that by finding the `package.json`
  for a given dependency and retrieving the version number within.
- Created `immediatelyResolvableDependenciesWithEditorRequirements`
  to help in `editorModelFromPersistentModel` so that tests can still
  more easily work without needing to resolve the dependencies.
- `fetchPackagerResponse` first gets the resolved version before pulling
  anything from JsDelivr.

### CODE REVIEW

File: editor/src/components/code-editor/script-editor.tsx [hunk 1]
```diff
@@ -348,8 +348,7 @@ export const ScriptEditor = betterReactMemo('ScriptEditor', (props: ScriptEditor
   const newErrorsForFile = errors.filter((error) => error.fileName === filePath)
   const errorsForFile = useKeepReferenceEqualityIfPossible(newErrorsForFile)
 
-  const newNpmDependencies = dependenciesFromPackageJson(packageJsonFile)
-  const npmDependencies = useKeepReferenceEqualityIfPossible(newNpmDependencies)
+  const npmDependencies = usePossiblyResolvedPackageDependencies()
```
Comment (balazsbajorics) [inline editor/src/components/code-editor/script-editor.tsx:351]: was this `useKeepReferenceEqualityIfPossible` redundant here? why was this added in the first place? was there a reason or was it just unnecessary caution?

File: editor/src/components/editor/actions/actions.ts [hunk 2]
```diff
@@ -4049,13 +4048,13 @@ export const UPDATE_FNS = {
...
   UPDATE_PACKAGE_JSON: (action: UpdatePackageJson, editor: EditorState): EditorState => {
     const dependencies = action.dependencies.reduce(
-      (acc: Array<NpmDependency>, curr: NpmDependency) => {
+      (acc: Array<RequestedNpmDependency>, curr: RequestedNpmDependency) => {
         return {
           ...acc,
           [curr.name]: curr.version,
         }
       },
-      {} as Array<NpmDependency>,
```
Comment (balazsbajorics) [inline editor/src/components/editor/actions/actions.ts:4058]: ` {} as Array<NpmDependency>,`

omg

File: editor/src/components/code-editor/script-editor.tsx (hunk 1 above)
Comment (seanparsons) [reply editor/src/components/code-editor/script-editor.tsx:351]: Not sure about the original case, but this _should_ be fine as there's some `useMemo` inside it for that kind of reason.

File: editor/src/components/editor/actions/actions.ts (hunk 2 above)
Comment (seanparsons) [reply editor/src/components/editor/actions/actions.ts:4058]: Yeah...

**Review by balazsbajorics — APPROVED** [review]

**Review by Rheeseyb — APPROVED** [review]
