### PR TITLE
Handle class exports.

### LINKED ISSUE #1713: Parser is broken for`export class Cica` and `export default class Cica`
`export class Cica` and `export default class Cica` do not show up on `exportsDetail` . 
This means the customRequireFn inside ui-jsx-canvas will return a broken import

### PR DESCRIPTION
**Pull request by seanparsons**
Fixes #1713

**Problem:**
If a class component is exported like `export class App` or `export default class App` it doesn't get exposed appropriately so that the canvas will supply the values when imported.

**Fix:**
Include class declarations in the pass which collates the exports, as they're flagged against class declarations with a modifier rather than export declarations.

**Commit Details:**
- Fixes #1713.
- `parseCode` now handles class declarations in the export details
  by checking if the declaration has the export keyword attached to it.

### CODE REVIEW

**Review by Rheeseyb — APPROVED** [review]

File: editor/src/core/workers/parser-printer/parser-printer.ts [hunk 1]
```diff
@@ -1201,8 +1201,34 @@ export function parseCode(
...
           pushArbitraryNode(exportDeclaration)
         })
-        // Handle imports.
+      } else if (
+        TS.isClassDeclaration(topLevelElement) &&
+        topLevelElement.modifiers != null &&
+        topLevelElement.modifiers.some((modifier) => modifier.kind === TS.SyntaxKind.ExportKeyword)
+      ) {
+        // Handle classes.
+        // Check if this is the 'default' export, which is to say the entire export for the file.
```
Comment (balazsbajorics) [inline editor/src/core/workers/parser-printer/parser-printer.ts:1210]: warning, helpful comment is not completely right: in the ESModules (this is how our ts code is compiled too), a module can have named exports -and- default exports simultaneously. The default export is attached under the name `default`...

**Review by balazsbajorics — APPROVED** [review]
