### PR TITLE
Minor fixes to focusing the classname section

### LINKED ISSUE #1620: Focus the classname input when expanding
When clicking to expand the classname selector, the input field should be focused.

### LINKED ISSUE #1623: Better expansion management of the Tailwind controls
**Problems**
- “When I click on expand button I’d expect (the classname input field) to have focus”
- "When I use the keyboard shortcut to focus class names input, it should expand the menu if not already expanded"

### PR DESCRIPTION
**Pull request by Rheeseyb**
Fixes #1620 
Fixes #1623 

**Problem:**
Expanding the classname section should focus the input control. Using the shortcut for the classname input field should ensure that the Inspector section is expanded.

**Fix:**
Added a `setTimeout` to focus the input ref when expanding the section. Compare the current `focusTriggerCount` with the previous to see if the section has been focused via the keyboard shortcut, and trigger the expanding logic if it wasn't already expanded.

### CODE REVIEW

File: editor/src/components/inspector/sections/style-section/className-subsection/className-subsection.tsx [hunk 1]
```diff
@@ -225,7 +225,31 @@ const ClassNameControl = betterReactMemo('ClassNameControl', () => {
   const isMenuEnabled = isSettable && elementPaths.length === 1
   const selectedOptionsLength = selectedOptions?.length ?? 0
   const [isExpanded, setIsExpanded] = React.useState(selectedOptionsLength > 0)
-  const toggleIsExpanded = React.useCallback(() => setIsExpanded((current) => !current), [])
+
+  const expandSection = React.useCallback(() => {
+    setIsExpanded(true)
+    window.setTimeout(() => inputRef.current?.focus(), 0)
```
Comment (seanparsons) [inline editor/src/components/inspector/sections/style-section/className-subsection/className-subsection.tsx:231]: if this is toggled rapidly can this fire at the wrong time? I'm thinking that the `setTimeout` call might need cancelling when contracted.

**Review by seanparsons — APPROVED** [review]

File: editor/src/components/inspector/sections/style-section/className-subsection/className-subsection.tsx (hunk 1 above)
Comment (Rheeseyb) [reply editor/src/components/inspector/sections/style-section/className-subsection/className-subsection.tsx:231]: Good point. In theory it shouldn't matter since the input will be destroyed, but I'll add the cancellation anyway.

Comment (Rheeseyb) [reply editor/src/components/inspector/sections/style-section/className-subsection/className-subsection.tsx]: Fixed in https://github.com/concrete-utopia/utopia/pull/1624/commits/e64adb9dfc7c75dc6bd8f8ef29c927095564e30e
