### PR TITLE
Fix/scaling controls why

### LINKED ISSUE #1598: Flex insert controls shouldn't grow when zooming
**Problem**
The on-canvas insert controls (from the experiment) grow and shrink with zoom.

**Solution Notes**
We have a pattern to address this (via the zoom factor we pass into props / editor state?).

Additionally, I suggest we solve this by passing in the desired _anchor point_ for the controls, and let them handle their own positioning without complex computations. We can accomplish that via `translate (-50% -50%)`  for centering.

### PR DESCRIPTION
**Pull request by balazsbajorics**
Fixes #1598

This PR fixes the scaling issues for the Plus Button Insert control and the floating parent layout control

### CODE REVIEW

File: editor/src/components/canvas/controls/insertion-plus-button.tsx [hunk 1]
```diff
@@ -275,6 +278,9 @@ const PlusButton = betterReactMemo('PlusButton', (props: ButtonControlProps) =>
     },
     [dispatch, parentPath, indexPosition],
   )
+
+  const ButtonSize = 12
```
Comment (Rheeseyb) [inline editor/src/components/canvas/controls/insertion-plus-button.tsx:282]: Was this supposed to be scaled too?

Comment (balazsbajorics) [reply editor/src/components/canvas/controls/insertion-plus-button.tsx:282]: nah, I'm using zoom and transorm: scale in this one because of the text

**Review by Rheeseyb — APPROVED** [review]
